-- Union of HKC, HKN, HRC, HRN Tables - used in Granular

CREATE OR REPLACE VIEW UnionAllTables AS
(SELECT 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_FarmerID')) AS FarmerID, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_SampleOrNot')) AS SampleOrNot, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0001_Season')) AS Season, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0002_TypeOfSchedule')) AS TypeOfSchedule, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000401_AgroclimaticZone')) AS AgroclimaticZone, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000402_AgroclimaticZoneCode')) AS AgroclimaticZoneCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000501_District')) AS District, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000502_DistrictCode')) AS DistrictCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000601_Mandal')) AS Mandal, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000602_MandalCode')) AS MandalCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000701_GP')) AS GP, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000702_GPCode')) AS GPCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0008_FarmerName')) AS FarmerName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0012_SocialCategory')) AS SocialCategory, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001501_InvestigatorName')) AS InvestigatorName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001502_InvestigatorCode')) AS InvestigatorCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0017_DateOfInterview')) AS DateOfInterview, 
'HKC' AS TableName 
FROM HKC)
UNION ALL
(SELECT 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_FarmerID')) AS FarmerID, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_SampleOrNot')) AS SampleOrNot, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0001_Season')) AS Season, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0002_TypeOfSchedule')) AS TypeOfSchedule, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000401_AgroclimaticZone')) AS AgroclimaticZone, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000402_AgroclimaticZoneCode')) AS AgroclimaticZoneCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000501_District')) AS District, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000502_DistrictCode')) AS DistrictCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000601_Mandal')) AS Mandal, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000602_MandalCode')) AS MandalCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000701_GP')) AS GP, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000702_GPCode')) AS GPCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0008_FarmerName')) AS FarmerName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0012_SocialCategory')) AS SocialCategory, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001501_InvestigatorName')) AS InvestigatorName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001502_InvestigatorCode')) AS InvestigatorCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0015_DateOfInterview')) AS DateOfInterview, 
'HKN' AS TableName 
FROM HKN)
UNION ALL 
(SELECT 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_FarmerID')) AS FarmerID, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_SampleOrNot')) AS SampleOrNot, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0001_Season')) AS Season, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0002_TypeOfSchedule')) AS TypeOfSchedule, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000401_AgroclimaticZone')) AS AgroclimaticZone, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000402_AgroclimaticZoneCode')) AS AgroclimaticZoneCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000501_District')) AS District, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000502_DistrictCode')) AS DistrictCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000601_Mandal')) AS Mandal, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000602_MandalCode')) AS MandalCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000701_GP')) AS GP, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000702_GPCode')) AS GPCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0008_FarmerName')) AS FarmerName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0012_SocialCategory')) AS SocialCategory, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001501_InvestigatorName')) AS InvestigatorName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001502_InvestigatorCode')) AS InvestigatorCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0017_DateOfInterview')) AS DateOfInterview, 
'HRC' AS TableName 
FROM HRC)
UNION ALL 
(SELECT 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_FarmerID')) AS FarmerID, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0000_SampleOrNot')) AS SampleOrNot, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0001_Season')) AS Season, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0002_TypeOfSchedule')) AS TypeOfSchedule, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000401_AgroclimaticZone')) AS AgroclimaticZone, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000402_AgroclimaticZoneCode')) AS AgroclimaticZoneCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000501_District')) AS District, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000502_DistrictCode')) AS DistrictCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000601_Mandal')) AS Mandal, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000602_MandalCode')) AS MandalCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000701_GP')) AS GP, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q000702_GPCode')) AS GPCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0008_FarmerName')) AS FarmerName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0012_SocialCategory')) AS SocialCategory, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001501_InvestigatorName')) AS InvestigatorName, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q001502_InvestigatorCode')) AS InvestigatorCode, 
JSON_UNQUOTE(JSON_EXTRACT(JSON_Data, '$.Q00.Q0017_DateOfInterview')) AS DateOfInterview, 
'HRN' AS TableName 
FROM HRN)
